services:
  order_api:
    build: .
    container_name: order_service_api
    image: atelie_order_api
    ports:
      - "8000:8000"
    networks:
      - atelie-network
    volumes:
      - .:/app
    env_file:
      - .env

  ngrok-orders:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: "http order_api:8000"
    ports:
      - "4040:4040"
    networks:
      - atelie-network
    depends_on:
      - order_api

networks:
  atelie-network:
    external: true
