"""include attribute in orders

Revision ID: 24d82df60a32
Revises: 7d165db0ae1c
Create Date: 2026-05-17 14:15:41.836901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d82df60a32'
down_revision: Union[str, Sequence[str], None] = '7d165db0ae1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('platform_fee', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('artisan_ammount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('checkout_group_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'checkout_group_id')
    op.drop_column('orders', 'artisan_ammount')
    op.drop_column('orders', 'platform_fee')
    # ### end Alembic commands ###
