"""add OrderStatus EXPIRED

Revision ID: c772e0abde2c
Revises: 24d82df60a32
Create Date: 2026-06-27 13:22:58.307223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c772e0abde2c'
down_revision: Union[str, Sequence[str], None] = '24d82df60a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE orderstatus ADD VALUE 'EXPIRED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
